# Generated by Django 5.0.6 on 2024-05-31 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_news_ip_address_alter_news_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.RenameField(
            model_name='news',
            old_name='updated_att',
            new_name='updated_at',
        ),
    ]
